In [ ]:
Dimensionality Reduction -- PCA
30 students in a class

math, sci, english  ====>  percentage marks

population dataset
30 features (X) -- independent variables
30 becomes 28 if we replace (math,sci,english) with percentage column

percentage should suffice what other columns (math,sci,eng) do

example -- telecom billing
customer 50 parameters
50 features -- reduce

-- less time space complexity -- becomes faster
-- more accuracy
-- reading dataset size -- 
-- easy visualization since less dimensions

In [ ]:
m independent variables, PCA extracts p (<=m) new independent variables that explains most of the 
variables of yout dataset -- new col 'p' is called principal component

In [31]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [17]:
df = pd.DataFrame(columns=['calories', 'breakfast', 'lunch', 'dinner','exercise', 'body_type'])
df.loc[0] = [1200,1,0,0,2,'skinny']
df.loc[1] = [2000,1,1,1,2,'normal']
df.loc[2] = [1400,1,0,0,2,'skinny']
df.loc[3] = [5000,1,0,0,2,'normal']
df.loc[4] = [1300,1,2,2,0,'fat']
df.loc[5] = [3000,2,2,0,2,'normal']
df.loc[6] = [2600,1,0,0,2,'fat']

In [18]:
df

calories breakfast lunch dinner exercise body_type
0     1200         1     0      0        2    skinny
1     2000         1     1      1        2    normal
2     1400         1     0      0        2    skinny
3     5000         1     0      0        2    normal
4     1300         1     2      2        0       fat
5     3000         2     2      0        2    normal
6     2600         1     0      0        2       fat

In [21]:
X = df.iloc[:, :-1]

In [22]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [23]:
pca = PCA(n_components=1)
pca_X = pca.fit_transform(X)

In [25]:
pca_X

array([[-0.66942597],
       [ 0.47575367],
       [-0.71981886],
       [-1.6268909 ],
       [ 3.63806052],
       [-0.07550225],
       [-1.02217621]])

In [26]:
result = pd.DataFrame(pca_X, columns=['PC1'])
result

PC1
0 -0.669426
1  0.475754
2 -0.719819
3 -1.626891
4  3.638061
5 -0.075502
6 -1.022176

In [27]:
result['label'] = df[['body_type']]

In [28]:
result

PC1   label
0 -0.669426  skinny
1  0.475754  normal
2 -0.719819  skinny
3 -1.626891  normal
4  3.638061     fat
5 -0.075502  normal
6 -1.022176     fat

### Reinforcement Learning

In [ ]:
Agent -- RL algorithm or machine that learns from trial and error
Environment -- world through which agent is moving
action -- possible steps that agent can take
state -- current condition returned by the environment
rewards -- points given by the env
policy -- approach -- need to explore all policies and decide

Agent performs actions for rewards.. it improvies actions for more rewards

In [ ]:
Q-Learning -- 

In [32]:
R = np.matrix([ [-1, -1, -1, -1, 0, -1 ],
                [-1, -1, -1, 0, -1, 100 ],
                [-1, -1, -1, 0, -1, -1 ],
                [-1, 0, 0, -1, 0, -1 ],
                [0, -1, -1, 0, -1, 100 ],
                [-1, 0, -1, -1, 0, 100 ] ])
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [34]:
# memory matrix -- agent has learned through experience
# rows -- state of agent
# cols -- possible actions -- leads to the next state
Q = np.matrix(np.zeros([6,6]))
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
Process:
    env sends states to agent
    agent performs actions
    env returns rewards/error

Exploration -- exploring and capturing more information about the env

In [36]:
initisla_state = 2
def get_available_actions(state):
    row = R[state]
    actions = np.where(R[state] >= 0)[1]
    return actions

In [40]:
available_actions = get_available_actions(3)
available_actions

array([1, 2, 4])

In [41]:
def next_action(available_actions):
    return np.random.choice(available_actions)

In [42]:
actions = get_available_actions(3)
action = next_action(actions)

In [44]:
actions

array([1, 2, 4])

In [52]:
np.where(Q[action] == np.max(Q[action]))[1].shape[0]

6

In [ ]:
# Q(state, action) = R(state, action) + 0.8 * Max(Q(next_state, all_actions))

In [54]:
def get_available_actions(state):
    row = R[state]
    actions = np.where(R[state] >= 0)[1]
    return actions

def next_action(available_actions):
    return np.random.choice(available_actions)

def update_q_matrix(current_state, action):
    max_index = np.where(Q[action] == np.max(Q[action]))[1]
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size=1))
    else:
        max_index = int(max_index)
    max_val = Q[action, max_index]
    Q[current_state, action] = R[current_state, action] + 0.8*max_val

In [53]:
# current_state = 1
# Q(1,5) = R(1,5) + 0.8*Max(Q(5,1)(5,5)(5,4))
# current_state = 2
# Q(2,3) = R(2,3) + 0.8*Max(Q(3,4)(3,1)(3,2))

In [55]:
initial_state = 2
actions = get_available_actions(initial_state)
actions

array([3])

In [56]:
action = next_action(actions)

In [58]:
action

3

In [59]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [60]:
for i in range(10000):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_actions = get_available_actions(current_state)
    action = next_action(available_actions)
    update_q_matrix(current_state, action)

In [61]:
Q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [320.,   0.,   0., 320.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [68]:
# Testing/evaluate
goal_state = 5
current_state = 3
# policy = [2,3,1,5]
steps = [current_state]
while current_state != goal_state:
    next_step_index = np.where(Q[current_state] == np.max(Q[current_state]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index
steps

[3, 1, 5]

In [70]:
! pip install gym

     |████████████████████████████████| 1.6MB 483kB/s eta 0:00:01     |█████                           | 245kB 483kB/s eta 0:00:03     |████████▍                       | 409kB 483kB/s eta 0:00:03
     |████████████████████████████████| 1.0MB 4.4MB/s eta 0:00:01
  Stored in directory: /home/gbhure/.cache/pip/wheels/c0/84/61/523b92d88787ae29689b3cc08cf445d8d8186d7fbe1acbf87b
Successfully built gym


In [71]:
import gym
env=gym.make('MountainCar-v0')
env.reset()
done = False
while not done:
    action = 2
    new_state, reward, done, _ = env.step(action)
    env.render()
env.close()