## Day3

In [1]:
names = ['THIRU', 'Ruban', 'Raj', 'abi', 'kothai', 'malar', 'New name', 'Aakash']

In [12]:
def filter_names(names):
    new_list = []
    for name in names:
        if len(name) > 5:
            new_list.append(name)
    return new_list

In [13]:
print(filter_names(names))

['kothai', 'New name', 'Aakash']


In [7]:
[ i for i in range(10) if i%2 == 1 ]

[1, 3, 5, 7, 9]

In [8]:
[ name for name in names if len(name) > 5]

['kothai', 'New name', 'Aakash']

In [31]:
def employee(name, age, *args):
    print(name, age)
    print(args[3])

In [32]:
employee('Aakash', 25, '+91 82763784', 'Pune', 'Male', 'Address lines')

Aakash 25
Address lines


In [42]:
def employee(name, age, **kwargs):
    print(name, age)
    print(kwargs['city'])

In [43]:
employee('Aakash', 25, city='Pune', mobile='+91 82763784', sex='Male', addr='Address lines')

Aakash 25
Pune


In [41]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [47]:
def hello(name, age, phoneno, *details):
    print ("I am ",name," and i am new to python")
    print ("non keyword arguments",details)
    return "Age is {}" .format(age)

In [48]:
hello('Aakash', 25, 9384)

I am  Aakash  and i am new to python
non keyword arguments ()


'Age is 25'

In [49]:
# is *args for variables, **args for tuple/list right ?

In [ ]:
# *args for tuple ---> *args is a tuple of all arguments
# **kwargs for dict --> **kwargs is a dict (of all keyword arguments)

In [50]:
# Lambda function --> Anonymous user defined function

In [58]:
def func(x, y):
    if x > y:
        return x-y
    else:
        return y-x

In [59]:
def func(x, y):
    return x-y if x>y else y-x

In [60]:
func(56,34)

22

In [55]:
f_obj = func

In [56]:
type(f_obj)

function

In [57]:
f_obj(34,67)

33

In [63]:
v = lambda x,y: x-y if x>y else y-x

In [64]:
type(v)

function

In [62]:
v(10,23)

13

In [67]:
def func(x):
    return x**3

In [68]:
map(func, [1,2])

In [70]:
numbers = [1,2,5,6,7]
cube = []
for n in numbers:
    cube.append(func(n))

In [71]:
cube

[1, 8, 125, 216, 343]

In [86]:
def func(x):
    return x**3
m = map(func, numbers)

In [87]:
m = map(lambda x: x**3, numbers)

In [74]:
for i in m:
    print(i)

1
8
125
216
343


In [77]:
f = filter(func, numbers)

In [78]:
for i in f:
    print(i)

1
2
5
6
7


In [79]:
def func(n):
    if n%2==1:
        return n

In [84]:
f = filter(func, numbers)

In [85]:
for i in f:
    print(i)

1
5
7


In [88]:
# class, objects
# file handling
# numpy, pandas, matplotlib

In [89]:
# built-in function
# object func
# user defined
# lambda function
# module function

In [92]:
import math

In [93]:
math.sqrt(25)

5.0

In [96]:
s = 'jython'
s.capitalize()

'Jython'

In [99]:
# Primitive datatypes -- int, float, str, list, dict, tuple
# circle1_name = 'A1'
# circle1_radius = 4.2
# circle1_color = 'Blue'

class Circle:
    radius = 4.2

In [100]:
c1 = Circle()

In [101]:
type(c1)

__main__.Circle

In [238]:
class Car():
    def __init__(self, color):
        print('init called')
        self.no_of_tyres = 4
        self.color = 'White'
    def __del__(self):
        print('del func')
    def move(self, direction):
        self.d = direction
        print('Moving in {} direction'.format(direction))

In [239]:
nano = Car('Blue')
merc = Car('white')
audi = Car('red')

init called
init called
init called


In [177]:
merc.no_of_tyres

4

In [178]:
merc.color

'White'

In [186]:
audi.color

'White'

In [190]:
del nano

del func


In [191]:
x = 10

In [192]:
x

10

In [193]:
del x

In [159]:
audi.no_of_tyres = 5

In [160]:
nano.no_of_tyres

4

In [161]:
audi.no_of_tyres

5

In [139]:
type(nano)

__main__.Car

In [140]:
# Car.move()

In [162]:
audi.move('right')

Moving in right direction


In [164]:
merc.move('left')

Moving in left direction


In [165]:
audi.d

'right'

In [166]:
merc.d

'left'

In [168]:
#nano.d

In [250]:
class Person:
    __name = 'Aakash'
    age = 26
    def walk(self):
        print('Walking')
    def get_name(self):
        print(self.__name)

In [251]:
p = Person()

In [253]:
p.get_name()

Aakash


In [183]:
dir(p)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'name',
 'walk']

In [197]:
class Vehicle:
    no_of_tyres = 4
class Luxury():
    ac_power = ''
class Car(Vehicle):
    steering_type = 'Manual'

In [198]:
merc = Car()

In [199]:
merc.steering_type

'Manual'

In [200]:
merc.no_of_tyres

4

In [224]:
fh = open('/Users/Ganesh/Desktop/Cognixia/14Dec19/newfile.txt')

In [225]:
s = fh.read()

In [226]:
type(s)

str

In [227]:
print(s)

Python is fun
learning python
end of file



In [217]:
fh.close()

In [223]:
with open('/Users/Ganesh/Desktop/Cognixia/14Dec19/newfile.txt') as fh:
    s = fh.read()
    print(s)
print('end')

Python is fun
learning python
end of file



In [230]:
with open('/Users/Ganesh/Desktop/Cognixia/14Dec19/newfile.txt') as fh:
    s = fh.readlines()
    print(s)
    #print(fh.readline())

['Python is fun\n', 'learning python\n', 'end of file\n']


In [231]:
with open('/Users/Ganesh/Desktop/Cognixia/14Dec19/student.csv') as fh:
    s = fh.read()
    print(s)

id,name,age
1,Aakash,25
2,Mohan,27



In [235]:
with open('/Users/Ganesh/Desktop/Cognixia/14Dec19/student.csv') as fh:
    print(fh.readlines()[1])
    #for line in fh:
        #print(line)

1,Aakash,25



In [202]:
!pwd

/Users/Ganesh/Desktop/Cognixia/14Dec19


In [203]:
import os

In [207]:
os.getcwd()

'/Users/Ganesh/Desktop/Cognixia/14Dec19'

In [210]:
type(fh)

_io.TextIOWrapper

In [237]:
with open('/Users/Ganesh/Desktop/Cognixia/14Dec19/sample.txt') as fh:
    for line in fh:
        if 'python' in line:
            print(line)

python is fun

lets apply python learning



In [ ]:
# Most popular libraries
numpy
pandas
scikit-learn
matplotlib
seaborn

In [254]:
import numpy

In [255]:
# ! pip install numpy

In [256]:
arr_1d = numpy.array([2,4,6,7,8,9])

In [257]:
type(arr_1d)

numpy.ndarray

In [258]:
import numpy as np

In [259]:
arr_1d = np.array([2,4,6,7,8,9])

In [260]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
arr2d = np.array((lst1, lst2))

In [261]:
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [263]:
a = np.arange(100)

In [264]:
type(a)

numpy.ndarray

In [267]:
a.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
np.arange(100).reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [273]:
a1 = np.arange(100)

In [274]:
a1.shape

(100,)

In [275]:
a2 = np.arange(100).reshape(10,10)

In [278]:
a2.ndim

2

In [279]:
a2.size

100

In [280]:
a1.ndim

1

In [281]:
np.sum(a2)

4950

In [282]:
arr_1d = np.array([2,4,6,7,6,6,6,7,9,9,2,2,8,9])

In [284]:
np.unique(arr_1d)

array([2, 4, 6, 7, 8, 9])

In [291]:
l1 = [2,3,4]
l2 = [5,6,7]
# expected output ---> [7, 9, 11]

In [292]:
sum(l1)

9

In [294]:
new_list = []
for i in range(len(l1)):
    new_list.append(l1[i]+l2[i])

In [295]:
new_list

[7, 9, 11]

In [296]:
[ (x+y) for x,y in zip(l1, l2) ]

[7, 9, 11]

In [1]:
import numpy as np

In [6]:
import time
lst1 = [ x for x in range(100000000) ]
lst2 = [ x for x in range(100000000) ]
t0 = time.time()
lst = [ (x+y) for x,y in zip(lst1, lst2) ]
print((time.time() - t0) * 1000)

53174.919843673706


In [7]:
lst[:20]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [5]:
a1 = np.arange(100000000)
a2 = np.arange(100000000)
t0 = time.time()
a = a1+a2
print((time.time() - t0) * 1000)

4045.485258102417


In [9]:
a[4:20]

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
arr = np.array([2,4,6,7,6,6,6,7,9,9,2,2,8,9])

In [11]:
arr[arr%2==0]

array([2, 4, 6, 6, 6, 6, 2, 2, 8])

In [1]:
import numpy as np
a = np.arange(50).reshape(10,5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [14]:
a[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
a[:3, 1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
a[2:6, 2:4].flatten()

array([12, 13, 17, 18, 22, 23, 27, 28])

In [5]:
a[2:6, 2:4]

array([[12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(100).reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [12]:
a1 = np.arange(10).reshape(5,2)
a2 = np.arange(10).reshape(5,2)
np.hstack((a1,a2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [14]:
a.sum()

1225

In [15]:
np.mean(a)

24.5

In [ ]:
# CRUD --> Create, read, update, delete
student = { 1: {"name": "aakash", "age": 25},
          2: {"name": "Mohan", "age": 25},
          3: {"name": "Vijay", "age": 25} 
          }

student[2]['age'] = 24